# Generated by Django 5.0 on 2024-12-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="page_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="page_styles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
