# Generated by Django 5.0 on 2024-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_session_page_html_session_page_styles"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="html_diff",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["session", "timestamp"], name="core_event_session_4dd4b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type"], name="core_event_type_a3ce08_idx"),
        ),
    ]
